# Generated by Django 3.0.5 on 2022-12-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshop', '0002_auto_20221219_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
