# Generated by Django 3.0.5 on 2022-12-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshop', '0003_auto_20221214_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='barand',
            new_name='category',
        ),
    ]
