# Generated by Django 3.0.5 on 2022-12-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshop', '0003_remove_product_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brandname',
        ),
    ]
