# Generated by Django 3.0.5 on 2022-12-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshop', '0004_auto_20221220_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandname',
            new_name='brand_name',
        ),
    ]
